/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author IceFox
 */
public class AddAClassGroup extends javax.swing.JFrame {
        
       String url = "jdbc:mysql://127.0.0.1:3306/";
       String dbName = "studentresultdb";
       String driver = "com.mysql.jdbc.Driver";
       String userName = "root";
       String password = "root";
    
    /**
     * Creates new form AddAClassGroup
     */
    public AddAClassGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CGroupID = new javax.swing.JTextField();
        CGroupName = new javax.swing.JTextField();
        CloseBT = new javax.swing.JButton();
        AddBT = new javax.swing.JButton();
        DeleteBT = new javax.swing.JButton();
        list1 = new java.awt.List();
        SearchBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Class Group Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, -1, -1));

        jLabel2.setText("Class Group ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(CGroupID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 142, -1));
        getContentPane().add(CGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 142, -1));

        CloseBT.setText("Close");
        CloseBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBTActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 40));

        AddBT.setText("Add");
        AddBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTActionPerformed(evt);
            }
        });
        getContentPane().add(AddBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 40));

        DeleteBT.setText("Delete This Class");
        DeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 380, 248));

        SearchBT.setText("See All Class Groups");
        SearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 389, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/ch.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTActionPerformed
        
         try {
              list1.clear();
            // load the driver into memory
            Class.forName(driver).newInstance();
            // create a connection. The first command line parameter is assumed to
            // be the MDB file in which data tables are held
            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
           


            Statement stmt = conn.createStatement();

            // replacing the ? with the Title

            
            ResultSet rs = stmt.executeQuery("Select * From ClassGroup");
            while (rs.next()) {
                // Adding requested data to the listbox in a side by side order
                list1.add(("ClassGroup ID = "+ rs.getObject(1)+ "   ") +(" ClassGroup Name = " + rs.getObject(2)+"   "));
            }

            // execute a query

            // close the objects
            rs.close();
            stmt.close();
            conn.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_SearchBTActionPerformed

    private void CloseBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBTActionPerformed
       dispose();
    }//GEN-LAST:event_CloseBTActionPerformed

    private void AddBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTActionPerformed
       
         try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "INSERT INTO ClassGroup Values (?,?)";
            PreparedStatement prest = conn.prepareStatement(sql);
            prest.setString(1, CGroupID.getText());
            prest.setString(2, CGroupName.getText());
            prest.executeUpdate();
            
 
            prest.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This ClassGroup ID/Name already Exists or is Invalid");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_AddBTActionPerformed

    private void DeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTActionPerformed
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "Delete From ClassGroup Where ClassGroupID = (?)";
            PreparedStatement prest = conn.prepareStatement(sql);
            prest.setString(1, CGroupID.getText());
            
            prest.executeUpdate();
            JOptionPane.showMessageDialog(null,"You Deleted ClassGroup : " + CGroupID.getText());
            
 
            prest.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            
        }

    }//GEN-LAST:event_DeleteBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAClassGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAClassGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAClassGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAClassGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAClassGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBT;
    private javax.swing.JTextField CGroupID;
    private javax.swing.JTextField CGroupName;
    private javax.swing.JButton CloseBT;
    private javax.swing.JButton DeleteBT;
    private javax.swing.JButton SearchBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
