/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author IceFox
 */
public class AddaModule extends javax.swing.JFrame {
       String url = "jdbc:mysql://127.0.0.1:3306/";
       String dbName = "studentresultdb";
       String driver = "com.mysql.jdbc.Driver";
       String userName = "root";
       String password = "root";
    /**
     * Creates new form AddCourseModule
     */
    public AddaModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LinktoCourse = new javax.swing.JButton();
        MID = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        MName = new javax.swing.JTextField();
        Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        CheckBT = new javax.swing.JButton();
        DeleteBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LinktoCourse.setText("Link a Module to a Course");
        LinktoCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinktoCourseActionPerformed(evt);
            }
        });
        getContentPane().add(LinktoCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));
        getContentPane().add(MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 12, 296, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 78, -1, -1));
        getContentPane().add(MName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 40, 300, -1));

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 78, -1, -1));

        jLabel1.setText("Module ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 15, -1, -1));

        jLabel2.setText("Module Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, -1, -1));

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, 536, 239));

        CheckBT.setText("Check Current Modules");
        CheckBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBTActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        DeleteBT.setText("Delete");
        DeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 11, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/Blue-Abstract-Background-Design.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
        
    }//GEN-LAST:event_CloseActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
      try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "INSERT INTO Module Values (?,?)";
            PreparedStatement prest = conn.prepareStatement(sql);
            prest.setString(1, MID.getText());
            prest.setString(2, MName.getText());
            prest.executeUpdate();
            
 
            prest.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This Module ID already Exists or is Invalid");
            e.printStackTrace();
        }

      
    }//GEN-LAST:event_AddActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
       
    }//GEN-LAST:event_list1ActionPerformed

    private void CheckBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBTActionPerformed
          try {
              list1.clear();
            // load the driver into memory
            Class.forName(driver).newInstance();
            // create a connection. The first command line parameter is assumed to
            // be the MDB file in which data tables are held
            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
           


            Statement stmt = conn.createStatement();

            // replacing the ? with the Title

            
            ResultSet rs = stmt.executeQuery("Select * From Module");
            while (rs.next()) {
                // Adding requested data to the listbox in a side by side order
                list1.add(("Module ID = "+ rs.getObject(1)+ "   ") +(" Module Name = " + rs.getObject(2)+"   "));
            }

            // execute a query

            // close the objects
            rs.close();
            stmt.close();
            conn.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CheckBTActionPerformed

    private void DeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTActionPerformed
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");

            String sql = "Delete From Module Where ModuleID = (?)";
            PreparedStatement prest = conn.prepareStatement(sql);
            prest.setString(1, MID.getText());
            
            prest.executeUpdate();
            JOptionPane.showMessageDialog(null,"You Deleted ModuleID : " + MID.getText());
            
 
            prest.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            
        }

    }//GEN-LAST:event_DeleteBTActionPerformed

    private void LinktoCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinktoCourseActionPerformed
       Link L = new Link();
       L.setVisible(true);
    }//GEN-LAST:event_LinktoCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddaModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddaModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton CheckBT;
    private javax.swing.JButton Close;
    private javax.swing.JButton DeleteBT;
    private javax.swing.JButton LinktoCourse;
    private javax.swing.JTextField MID;
    private javax.swing.JTextField MName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
