/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;

/**
 *
 * @author IceFox
 */
public class AdminOptions extends javax.swing.JFrame {
      

    /**
     * Creates new form TeacherOptions
     */
    public AdminOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CPassBT = new javax.swing.JButton();
        AddStudent = new javax.swing.JButton();
        AddMod = new javax.swing.JButton();
        AddGroup = new javax.swing.JButton();
        StuInCourse = new javax.swing.JButton();
        AddCourse = new javax.swing.JButton();
        ModInCourse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        SearchStudent = new javax.swing.JButton();
        SearchExam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Advanced Options/Records");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 180, -1));

        CPassBT.setText("Change Passwords");
        CPassBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPassBTActionPerformed(evt);
            }
        });
        getContentPane().add(CPassBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        AddStudent.setText("Add/Delete Student");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        getContentPane().add(AddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 260, -1));

        AddMod.setText("Add/Delete Module");
        AddMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddModActionPerformed(evt);
            }
        });
        getContentPane().add(AddMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 260, -1));

        AddGroup.setText("Add / Delete/ See All Class Groups");
        AddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGroupActionPerformed(evt);
            }
        });
        getContentPane().add(AddGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 260, -1));

        StuInCourse.setText("See All Students in a Course");
        StuInCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuInCourseActionPerformed(evt);
            }
        });
        getContentPane().add(StuInCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 260, -1));

        AddCourse.setText("Add/Delete/See  Courses");
        AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseActionPerformed(evt);
            }
        });
        getContentPane().add(AddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 260, -1));

        ModInCourse.setText("See All Modules in a Course");
        ModInCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModInCourseActionPerformed(evt);
            }
        });
        getContentPane().add(ModInCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Admin Option Menu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, -1));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 50));

        SearchStudent.setText("Search/Edit Student by ID");
        SearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentActionPerformed(evt);
            }
        });
        getContentPane().add(SearchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 260, -1));

        SearchExam.setText("Search Exam by ID / Add Result");
        SearchExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchExamActionPerformed(evt);
            }
        });
        getContentPane().add(SearchExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/ch.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 560, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentActionPerformed
       SearchStudent S = new SearchStudent();
       S.setVisible(true);
    }//GEN-LAST:event_SearchStudentActionPerformed

    private void SearchExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchExamActionPerformed
        SearchExam E = new SearchExam();
        E.setVisible(true);
    }//GEN-LAST:event_SearchExamActionPerformed

    private void StuInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuInCourseActionPerformed
        StudentCourse SC = new StudentCourse();
        SC.setVisible(true);
    }//GEN-LAST:event_StuInCourseActionPerformed

    private void ModInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModInCourseActionPerformed
        ModuleCourse M = new ModuleCourse();
        M.setVisible(true);
    }//GEN-LAST:event_ModInCourseActionPerformed

    private void AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseActionPerformed
       AddaCourse A = new AddaCourse();
       A.setVisible(true);
    }//GEN-LAST:event_AddCourseActionPerformed

    private void AddModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddModActionPerformed
       AddaModule AM = new AddaModule();
       AM.setVisible(true);
    }//GEN-LAST:event_AddModActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
       AddAStudent ASA = new AddAStudent();
       ASA.setVisible(true);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void AddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGroupActionPerformed
        AddAClassGroup ACG = new AddAClassGroup();
        ACG.setVisible(true);
    }//GEN-LAST:event_AddGroupActionPerformed

    private void CPassBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPassBTActionPerformed
        ChangePass CP = new ChangePass();
        CP.setVisible(true);
    }//GEN-LAST:event_CPassBTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdvancedRecords AR = new AdvancedRecords();
        AR.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCourse;
    private javax.swing.JButton AddGroup;
    private javax.swing.JButton AddMod;
    private javax.swing.JButton AddStudent;
    private javax.swing.JButton CPassBT;
    private javax.swing.JButton ModInCourse;
    private javax.swing.JButton SearchExam;
    private javax.swing.JButton SearchStudent;
    private javax.swing.JButton StuInCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
