/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author IceFox
 */
public class ChangePass extends javax.swing.JFrame {
     
     String TPass ;
     String APass ;
     
    /**
     * Creates new form ChangePass
     */
    public ChangePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TP = new javax.swing.JButton();
        AP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TP.setText("Change Teacher Pass");
        TP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPActionPerformed(evt);
            }
        });
        getContentPane().add(TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 191, -1));

        AP.setText("Change Admin Pass");
        AP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APActionPerformed(evt);
            }
        });
        getContentPane().add(AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 191, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/Background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -2, 210, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPActionPerformed
            
        
            String Input =  JOptionPane.showInputDialog("Please Enter in The Current Teacher Password :");
             if (Input.equals(Passwords.Pass.getTeachPass())){
             
                 TPass = JOptionPane.showInputDialog("Please Enter in The New Teacher Password");
                 if (TPass.equals(TPass)){
                 
                     Passwords.Pass.setTeachPass(TPass);
                     JOptionPane.showMessageDialog(null, "New Teacher Password = " +Passwords.Pass.getTeachPass());
                     ChangePass.this.dispose();
                 }
                 
             }
             else JOptionPane.showMessageDialog(null, "Incorrect Password.Please Try Again");
    }//GEN-LAST:event_TPActionPerformed

    private void APActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APActionPerformed
       
        
        String Input2 =  JOptionPane.showInputDialog("Please Enter in The Current Admin Password :");
             if (Input2.equals(Passwords.Pass.getAdminPass())){
             
                 APass = JOptionPane.showInputDialog("Please Enter in The New Admin Password");
                 if (APass.equals(APass)){
                 
                     Passwords.Pass.setAdminPass(APass);
                     JOptionPane.showMessageDialog(null, "New Admin Password = " +Passwords.Pass.getAdminPass());
                     ChangePass.this.dispose();
                 
                 }
                 
             }
             else JOptionPane.showMessageDialog(null, "Incorrect Password.Please Try Again");
    }//GEN-LAST:event_APActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AP;
    private javax.swing.JButton TP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
