/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;
import java.sql.*;
import javax.swing.JOptionPane;
       

/**
 *
 * @author IceFox
 */
public class SearchStudent extends javax.swing.JFrame {

        String url = "jdbc:mysql://127.0.0.1:3306/";
       String dbName = "studentresultdb";
       String driver = "com.mysql.jdbc.Driver";
       String userName = "root";
       String password = "root";
       StudentINFO SI = new StudentINFO();
       
       
       
    
    /**
     * Creates new form SearchStudent
     */
    public SearchStudent() {
        initComponents();
       
    }
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        UpdateBT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ClearBT = new javax.swing.JButton();
        ID2Class = new javax.swing.JButton();
        ID2Name = new javax.swing.JButton();
        SNameTF = new javax.swing.JTextField();
        SAddTF = new javax.swing.JTextField();
        SDOBTF = new javax.swing.JTextField();
        SPhoneTF = new javax.swing.JTextField();
        SGroupTF = new javax.swing.JTextField();
        CIDTF = new javax.swing.JTextField();
        StuIDTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameID = new javax.swing.JTextField();
        searchBT2 = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        closebt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateBT.setText("Update This Student");
        UpdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(DD/MM/YY)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        ClearBT.setText("Clear");
        ClearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        ID2Class.setText("Class Name");
        ID2Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID2ClassActionPerformed(evt);
            }
        });
        getContentPane().add(ID2Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 100, -1));

        ID2Name.setText("Course Name");
        ID2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID2NameActionPerformed(evt);
            }
        });
        getContentPane().add(ID2Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));
        getContentPane().add(SNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, -1));
        getContentPane().add(SAddTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 230, -1));
        getContentPane().add(SDOBTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 230, -1));
        getContentPane().add(SPhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 230, -1));
        getContentPane().add(SGroupTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 230, -1));
        getContentPane().add(CIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));
        getContentPane().add(StuIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Class Group:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CourseID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        NameID.setText("Enter Name or ID of Student......");
        getContentPane().add(NameID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, -1));

        searchBT2.setText("Search by ID");
        searchBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBT2ActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        searchBT.setText("Search by Name");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        getContentPane().add(searchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        closebt.setText("Close");
        closebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtActionPerformed(evt);
            }
        });
        getContentPane().add(closebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/267760-cool-background-images-1920x1200.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtActionPerformed
        dispose();
    }//GEN-LAST:event_closebtActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
    
       
        
       
        
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "SELECT * FROM Student WHERE Student_Name = ?";
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(1, NameID.getText());
            

            // replacing the ? with the Title
             ResultSet rs = prest.executeQuery();
           
             // stop search if item is not in database
            if (!(rs.first() == false)){
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
                StuIDTF.setText(rs.getString(1));
                SNameTF.setText(rs.getString(2));
                SAddTF.setText(rs.getString(3));
                SDOBTF.setText(rs.getString(4));
                SPhoneTF.setText(rs.getString(5));
                SGroupTF.setText(rs.getString(6));
                CIDTF.setText(rs.getString(7));
                
                
               
                
            
            }
                // close the objects
                rs.close();
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

      

    }//GEN-LAST:event_searchBTActionPerformed
 
 

    private void ID2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID2NameActionPerformed
           
        
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "SELECT * FROM Course WHERE CourseID = ?";
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(1, CIDTF.getText());
            

            // replacing the ? with the Title
             ResultSet rs = prest.executeQuery();
           
             // stop search if item is not in database
            if (!(rs.first() == false)){
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
                
                CIDTF.setText(rs.getString(2));
                
            
            }
                // close the objects
                rs.close();
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ID2NameActionPerformed

    private void searchBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBT2ActionPerformed
        
        
       
        
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "SELECT * FROM Student WHERE StudentID = ?";
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(1, NameID.getText());
            

            // replacing the ? with the Title
             ResultSet rs = prest.executeQuery();
           
             // stop search if item is not in database
            if (!(rs.first() == false)){
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
                StuIDTF.setText(rs.getString(1));
                SNameTF.setText(rs.getString(2));
                SAddTF.setText(rs.getString(3));
                SDOBTF.setText(rs.getString(4));
                SPhoneTF.setText(rs.getString(5));
                SGroupTF.setText(rs.getString(6));
                CIDTF.setText(rs.getString(7));
                
                
                
            
            }
                // close the objects
                rs.close();
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_searchBT2ActionPerformed

    private void ID2ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID2ClassActionPerformed
          
       try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "SELECT * FROM classgroup WHERE ClassGroupID = ?";
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(1, SGroupTF.getText());
            

            // replacing the ? with the Title
             ResultSet rs = prest.executeQuery();
           
             // stop search if item is not in database
            if (!(rs.first() == false)){
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
                
                SGroupTF.setText(rs.getString(2));
                
            
            }
                // close the objects
                rs.close();
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ID2ClassActionPerformed

    private void ClearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTActionPerformed
       StuIDTF.setText("");
       SNameTF.setText("");
       SAddTF.setText("");
       SDOBTF.setText("");
       SGroupTF.setText("");
       SPhoneTF.setText("");
       CIDTF.setText("");
    }//GEN-LAST:event_ClearBTActionPerformed

    private void UpdateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTActionPerformed
           
            String Input =  JOptionPane.showInputDialog("Please Enter in The Admin Password :");
             if (Input.equals(Passwords.Pass.getAdminPass())){
             
             // Bringing Forth the Fields to the Update Student Form for Updating. 
                SI.setStuID(StuIDTF.getText());
                SI.setStuName(SNameTF.getText());
                SI.setStuAdd(SAddTF.getText());
                SI.setStuDOB(SDOBTF.getText());
                SI.setStuGroup(SGroupTF.getText());
                SI.setStuPhone(SPhoneTF.getText());
                SI.setStuCourse(CIDTF.getText());
                
        
        
        UpdateStudent US = new UpdateStudent();
        
        US.StudentID = SI.getStuID();
        US.StudentName = SI.getStuName();
        US.StudentAdd = SI.getStuAdd();
        US.StudentDate = SI.getStuDOB();
        US.StudentGroup = SI.getStuGroup();
        US.StudentPhone = SI.getStuPhone();
        US.StudentCourse = SI.getStuCourse();
        
        System.out.print(SI.getStuDOB());
        
        US.setVisible(true);
             
             }
             else {
             
             JOptionPane.showMessageDialog(null, "Incorrect Password");
             
             }
                

      
     
     
    
     
    
     
     
     
     
     
     
    }//GEN-LAST:event_UpdateBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStudent().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CIDTF;
    private javax.swing.JButton ClearBT;
    private javax.swing.JButton ID2Class;
    private javax.swing.JButton ID2Name;
    private javax.swing.JTextField NameID;
    private javax.swing.JTextField SAddTF;
    private javax.swing.JTextField SDOBTF;
    private javax.swing.JTextField SGroupTF;
    private javax.swing.JTextField SNameTF;
    private javax.swing.JTextField SPhoneTF;
    private javax.swing.JTextField StuIDTF;
    private javax.swing.JButton UpdateBT;
    private javax.swing.JButton closebt;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton searchBT;
    private javax.swing.JButton searchBT2;
    // End of variables declaration//GEN-END:variables
}

