/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;
import com.sun.corba.se.spi.orbutil.fsm.Guard;
import java.sql.*;

/**
 *
 * @author IceFox
 */
public class SearchExam extends javax.swing.JFrame {
       String url = "jdbc:mysql://127.0.0.1:3306/";
       String dbName = "studentresultdb";
       String driver = "com.mysql.jdbc.Driver";
       String userName = "root";
       String password = "root";
       
       GetOverallResult GOR = new GetOverallResult();
       
    

    
    
     
  
     
    
    /**
     * Creates new form SearchExam
     */
    public SearchExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyBT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddExamBT = new javax.swing.JButton();
        modID = new javax.swing.JTextField();
        StuID = new javax.swing.JTextField();
        SearchBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        Overall = new javax.swing.JTextField();
        closebt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModifyBT.setText("Modify");
        ModifyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBTActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Do not enter anything for Overall Result.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("%");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 30, 20));

        AddExamBT.setText("Add New Result");
        AddExamBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddExamBTActionPerformed(evt);
            }
        });
        getContentPane().add(AddExamBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        modID.setText("Enter Module ID.....");
        modID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modIDKeyTyped(evt);
            }
        });
        getContentPane().add(modID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, -1));

        StuID.setText("Enter Student ID......");
        StuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuIDActionPerformed(evt);
            }
        });
        StuID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StuIDKeyTyped(evt);
            }
        });
        getContentPane().add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, -1));

        SearchBT.setText("Search");
        SearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Assessment 1 :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Assessment 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assessment 3:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Overall Result:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, -1, -1));

        A1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A1KeyTyped(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 132, 257, -1));

        A2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A2KeyTyped(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 158, 257, -1));

        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        A3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A3KeyTyped(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 184, 257, -1));

        Overall.setText("Click Here To Get Overall");
        Overall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverallMouseClicked(evt);
            }
        });
        getContentPane().add(Overall, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 257, -1));

        closebt.setText("Close");
        closebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtActionPerformed(evt);
            }
        });
        getContentPane().add(closebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/default-bg.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("%");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void StuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuIDActionPerformed
       
       
    }//GEN-LAST:event_StuIDActionPerformed
    
    private void closebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtActionPerformed
        dispose();
    }//GEN-LAST:event_closebtActionPerformed
    
    private void SearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTActionPerformed
      
        
         try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "SELECT * FROM Exam WHERE StudentID = ? AND ModuleID = ? ";
            
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(1, StuID.getText());
            prest.setString(2, modID.getText());
            

            // replacing the ? with the Title
             ResultSet rs = prest.executeQuery();
           
             // stop search if item is not in database
            if (!(rs.first() == false)){
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
                 
                
                
                A1.setText(rs.getString(3));
                A2.setText(rs.getString(4));
                A3.setText(rs.getString(5));
                
               
                
               
                
                
               
                
                
                
            
            }
                // close the objects
                rs.close();
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_SearchBTActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void AddExamBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddExamBTActionPerformed
        try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "INSERT INTO Exam (StudentID,ModuleID,Assessment1,Assessment2,Assessment3) Values (?,?,?,?,?)";
                
            
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
            
           
            prest.setString(1, StuID.getText());
            prest.setString(2, modID.getText());
            prest.setString(3, A1.getText());
            prest.setString(4, A2.getText());
            prest.setString(5, A3.getText());
            
             
                

            
              prest.executeUpdate();
           
           
            {
                

               
                 
                
                
                
                
            
            }
                // close the objects
                
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddExamBTActionPerformed
  
    private void ModifyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBTActionPerformed
        try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "UPDATE Exam SET Assessment1=?,Assessment2=?,Assessment3=? WHERE StudentID = ? AND ModuleID = ?";
                
            
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(4, StuID.getText());
            prest.setString(5, modID.getText());
            prest.setString(1, A1.getText());
            prest.setString(2, A2.getText());
            prest.setString(3, A3.getText());
            

            // replacing the ? with the Title
              prest.executeUpdate();
           
             // stop search if item is not in database
            {
                

                //PASING INFORMATION FROM DATABSE TO THE CLASS OBJECTS
//                eb.setISBN(rs.getString(1));
//                eb.setAuthor(rs.getString(3));
//                eb.setRRP(rs.getDouble(5));
                 //PASSING INFORMATION FROM OBJECT TO TEXTFIELDS
               
                
                
                 
                
                
                
                
            
            }
                // close the objects
                
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ModifyBTActionPerformed

    private void OverallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverallMouseClicked
       
        GOR.setN1(Double.parseDouble(A1.getText()));
        GOR.setN2(Double.parseDouble(A2.getText()));
        GOR.setN3(Double.parseDouble(A3.getText()));
        
        Double All = GOR.getN1()+GOR.getN2()+GOR.getN3();
        Double ResultX = All/3;
        
        Overall.setText(ResultX+"");
        
        
    }//GEN-LAST:event_OverallMouseClicked

    private void modIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modIDKeyTyped
      char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
           
       
    }//GEN-LAST:event_modIDKeyTyped

    private void StuIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StuIDKeyTyped
      char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
           
       
    }//GEN-LAST:event_StuIDKeyTyped

    private void A1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A1KeyTyped
        char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
           
       
    }//GEN-LAST:event_A1KeyTyped

    private void A2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A2KeyTyped
       char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
           
       
    }//GEN-LAST:event_A2KeyTyped

    private void A3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A3KeyTyped
        char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
           
       
    }//GEN-LAST:event_A3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JButton AddExamBT;
    private javax.swing.JButton ModifyBT;
    private javax.swing.JTextField Overall;
    private javax.swing.JButton SearchBT;
    private javax.swing.JTextField StuID;
    private javax.swing.JButton closebt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modID;
    // End of variables declaration//GEN-END:variables
}
