/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;

import javax.swing.JOptionPane;

/**
 *
 * @author IceFox
 */
public class TeacherLogin extends javax.swing.JFrame {
 
    
    
    /**
     * Creates new form TeacherLogin
     */
    public TeacherLogin() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginBT = new javax.swing.JButton();
        CloseBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernametfKeyPressed(evt);
            }
        });
        getContentPane().add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 33, 145, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        LoginBT.setText("Login");
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });
        LoginBT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginBTKeyPressed(evt);
            }
        });
        getContentPane().add(LoginBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 97, -1, -1));

        CloseBT.setText("Close");
        CloseBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBTActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 97, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher Login:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        passwordtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtfKeyPressed(evt);
            }
        });
        getContentPane().add(passwordtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 71, 148, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/Background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 260, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBTActionPerformed
       dispose();
    }//GEN-LAST:event_CloseBTActionPerformed
    
    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        TeacherOptions T = new TeacherOptions();
        String utf = usernametf.getText();
        String ptf = passwordtf.getText();
        
        if (utf.equalsIgnoreCase("TeacherQQI") && ptf.equals(Passwords.Pass.getTeachPass())){
            TeacherLogin.this.dispose();
            T.setVisible(true);
            
            
           
            
        }
        else {
        JOptionPane.showMessageDialog(null,"Incorrect UserName or Password");
        }
              
           
        
        
            
        
     
        
        
        
        
                
    }//GEN-LAST:event_LoginBTActionPerformed

    private void LoginBTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginBTKeyPressed
    
    }//GEN-LAST:event_LoginBTKeyPressed

    private void usernametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametfKeyPressed
        int keycode = evt.getKeyCode();
if(keycode == evt.VK_ENTER){
    
    passwordtf.grabFocus();
    
}

    }//GEN-LAST:event_usernametfKeyPressed

    private void passwordtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtfKeyPressed
            int keycode = evt.getKeyCode();
if(keycode == evt.VK_ENTER){
    
    TeacherOptions T = new TeacherOptions();
        String utf = usernametf.getText();
        String ptf = passwordtf.getText();
        
        if (utf.equalsIgnoreCase("TeacherQQI") && ptf.equals(Passwords.Pass.getTeachPass())){
            TeacherLogin.this.dispose();
            T.setVisible(true);
            
            
           
            
        }
        else {
        JOptionPane.showMessageDialog(null,"Incorrect UserName or Password");
        }
           
    
}
    }//GEN-LAST:event_passwordtfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBT;
    private javax.swing.JButton LoginBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
