/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;
import java.sql.*;
import javax.swing.JOptionPane;
       

/**
 *
 * @author IceFox
 */
public class UpdateStudent extends javax.swing.JFrame  {

       String url = "jdbc:mysql://127.0.0.1:3306/";
       String dbName = "studentresultdb";
       String driver = "com.mysql.jdbc.Driver";
       String userName = "root";
       String password = "root";
       
    String StudentID;
    String StudentName;
    String StudentAdd;
    String StudentDate;
    String StudentGroup;
    String StudentPhone;
    String StudentCourse;
        
       
       
       StudentINFO SI = new StudentINFO();
       
       
       
      
      
 
       
       
      
    /**
     * Creates new form SearchStudent
     */
    public UpdateStudent() {
        initComponents();
       
    }
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        SDOB = new javax.swing.JFormattedTextField();
        UpdateBT = new javax.swing.JButton();
        SName = new javax.swing.JTextField();
        SAdd = new javax.swing.JTextField();
        SPhone = new javax.swing.JTextField();
        SGroup = new javax.swing.JTextField();
        CID = new javax.swing.JTextField();
        StuID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        closebt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(DD/MM/YYYY)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 120, 100, 20));

        try {
            SDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        SDOB.setText(SDOB.getText());
        getContentPane().add(SDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 230, -1));

        UpdateBT.setText("Update Changed Fields");
        UpdateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 40));

        SName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SNameKeyTyped(evt);
            }
        });
        getContentPane().add(SName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, -1));
        getContentPane().add(SAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, -1));

        SPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SPhoneKeyTyped(evt);
            }
        });
        getContentPane().add(SPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, -1));
        getContentPane().add(SGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, -1));
        getContentPane().add(CID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 30));

        StuID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StuIDKeyTyped(evt);
            }
        });
        getContentPane().add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Class Group:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CourseID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        closebt.setText("Close");
        closebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtActionPerformed(evt);
            }
        });
        getContentPane().add(closebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/default-bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void closebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtActionPerformed
    dispose();
    }//GEN-LAST:event_closebtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        StuID.setText(StudentID);
        SName.setText(StudentName);
        SAdd.setText(StudentAdd);
        SDOB.setText(StudentDate);
        SGroup.setText(StudentGroup);
        SPhone.setText(StudentPhone);
        CID.setText(StudentCourse);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
      
    }//GEN-LAST:event_formWindowGainedFocus

    private void UpdateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTActionPerformed
         try {
            Class.forName(driver).newInstance();

            System.out.println("Connecting to the Database " + dbName + "....");
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            System.out.println("Database Connection Successful");
            
             String sql = "UPDATE Student SET StudentID = ?,Student_Name = ?,Student_Address = ?,Student_DOB = ?,Student_Phone = ?,Class_Group = ?,CourseID = ?  WHERE StudentID = ? ";
                
            
            
             
             PreparedStatement prest = conn.prepareStatement(sql);
             
            prest = conn.prepareStatement(sql);
            
             // replacing the ? with the Title
           
            prest.setString(8,StudentID);
            prest.setString(1, StuID.getText());
            prest.setString(2, SName.getText());
            prest.setString(3, SAdd.getText());
            prest.setString(4, SDOB.getText());
            prest.setString(5, SPhone.getText());
            prest.setString(6, SGroup.getText());
            prest.setString(7,CID.getText());
            

              prest.executeUpdate();
           
            
            {
                

      
               
          
                
                
            
            }
                // close the objects
                JOptionPane.showMessageDialog(null, "You Changed StudentID "+StudentID+ " Information");
                prest.close();
                conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateBTActionPerformed

    private void StuIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StuIDKeyTyped
        char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
            if (StuID.getText().length()>8){
            evt.consume();
            }
    }//GEN-LAST:event_StuIDKeyTyped

    private void SNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SNameKeyTyped
       char chartyped = evt.getKeyChar();
        if(!(Character.isAlphabetic(chartyped)||Character.isISOControl(chartyped)||Character.isSpace(chartyped)))
            evt.consume();
    }//GEN-LAST:event_SNameKeyTyped

    private void SPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SPhoneKeyTyped
         char chartyped = evt.getKeyChar();
        if(!(Character.isDigit(chartyped)||Character.isISOControl(chartyped))){
        evt.consume();
        }
            if (SPhone.getText().length()>12){
            evt.consume();
            }
            
    }//GEN-LAST:event_SPhoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CID;
    private javax.swing.JTextField SAdd;
    private javax.swing.JFormattedTextField SDOB;
    private javax.swing.JTextField SGroup;
    private javax.swing.JTextField SName;
    private javax.swing.JTextField SPhone;
    private javax.swing.JTextField StuID;
    private javax.swing.JButton UpdateBT;
    private javax.swing.JButton closebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}

